name: test

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        ruby_version:
          - 3.2
          - 3.1
          - "3.0"
          - 2.7
          - 2.6
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kenchan0130/actions-system-info@1.2.0
        id: system-info
      - name: Cache rubygems
        uses: actions/cache@v3.2.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-rubygems-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.system-info.outputs.release }}-rubygems-${{ matrix.ruby_version }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install dependencies
        shell: bash
        run: |
          set -eux
          bundle config path vendor/bundle
          bundle install --jobs "${{ steps.system-info.outputs.cpu-core }}" --retry 3
      - name: Run tests
        run: bundle exec rake
      - name: Output versions
        if: always()
        shell: bash
        run: |
          set -eux
          run_if_exist() {
            if test "x$(which $1)" != "x"
            then
              "$@"
            fi
          }
          uname -a
          run_if_exist sw_vers # macos
          run_if_exist lsb_release --all # ubuntu
          ruby --version
          gem --version
          bundle --version
      - name: Output gem versions
        if: always()
        run: bundle list
      - name: Output deb package versions
        if: always() && matrix.os == 'ubuntu'
        run: dpkg -l
